### ISSUE TITLE
Namespace System.Collections.Generic

### ISSUE THREAD

**Issue by plachor** [alhardy/AppMetrics.Extensions.Graphite#17]
Hi I control log level upon namespace in my app. Using this approach I would like to set default log-level for App.Metrics to Error for an example. But I found that this extension is using `System.Collections.Generic` namespace. This causes me a lot of pain. As my console is flooded with messages.

https://github.com/AppMetrics/Graphite/blob/dev/src/App.Metrics.Extensions.Reporting.Graphite/Client/Extensions/UdpGraphitePayloadListExtensions.cs

Are there any chances you will update this namespace to app.metrics.. ?

**Comment by alhardy** [comment]
Is this in your Dev environment?  Logs are written as trace level in that class, that wouldn't be good in production. You could for now filter on the logger type as well as namespace?

**Comment by plachor** [comment]
Thanks for quick response, yes it dev. I have not tried yet with logger type (I'll check if Serilog is capable of such filter). As to log level in both extension methods (UPD and TCP) you have line `logger.LogDebug(text);`. So the payload is logged with debug level. It would be great if it was Trace also.

--- 

Logger type worked out too 👍

**Comment by alhardy** [comment]
Yeah no worries, can change that to trace level

**Comment by plachor** [comment]
Thanks :)
