### ISSUE TITLE
Allow adding a prefix to the metrics

### ISSUE THREAD

**Issue by marcus-held** [alhardy/AppMetrics.Extensions.Graphite#30]
Hi,

I'd like to add a prefix to each metric that is sent to graphite, because our company shares one graphite and sorts metrics by common prefixes.

I helped myself by implementing my own `IGraphitePointTextWriter`, but would be nice to have this configurable.

**Comment by alhardy** [comment]
Possible to use https://www.app-metrics.io/getting-started/fundamentals/tagging-organizing/#metric-contexts?

**Comment by marcus-held** [comment]
I need the prefix on existing metrics, so this is not working unfortunately.

**Comment by alhardy** [comment]
@mld-ger https://github.com/AppMetrics/Graphite/issues/31
