### ISSUE TITLE
Exclude metric type from name during report to Graphite

### ISSUE THREAD

**Issue by vhatsura** [alhardy/AppMetrics.Extensions.Graphite#31]
First of all, big thank for awesome tool.

E.g., I have the following `GaugeOptions`:
```CSharp
var gaugeOptions = new GaugeOptions { Name = "test" };
```
and then set value for gauge:
```CSharp
MetricsContext.Measure.Gauge.SetValue(gaugeOptions , 1);
```
When I look to graphite I found metric by the `gauge.test` path.

Is it possible to somehow exclude metric type (in above case is `gauge`) from metric name?

**Comment by alhardy** [comment]
Thanks!

You could provide a custom `IGraphitePointTextWriter` to acheive that. You have complete control over series names with this.

```
 Metrics = new MetricsBuilder()
                      .Report.ToGraphite(
                          GraphiteUrl,
                          TimeSpan.FromSeconds(5),
                          optionsSetup: options => options.MetricPointTextWriter = new MyCustomPointWriter())
                      .Build();
```
