### ISSUE TITLE
Template based format for graphite endpoint

### ISSUE THREAD

**Issue by Yshayy** [alhardy/AppMetrics.Extensions.Graphite#8]
Hi,
As graphite is limited in it's query capabilities, it'll be extremely valuable to control the metric name using template, like the first implementation: https://github.com/alhardy/AppMetrics.Extensions.Graphite/blob/c04dd30be4f012f7fa6b870b88d0b22e95803826/src/App.Metrics.Extensions.Reporting.Graphite/Client/GraphiteMetricNameFormatter.cs 

It allow us to create metrics using templates like this:
{type}.{tag:host}.{context}.{tag:route}.{nameWithUnit}.{tag:http_status_code}

**Comment by alhardy** [comment]
@Yshayy Tag names are already dot separated but do only appear after the metric and context names. If you think more control is necessary I can provide some type of hook to provide more flexibility?

**Comment by Yshayy** [comment]
I think the problem with graphite is that adding a tag or reordering tags change graphite metrics name (which means it can require also changing dashboard settings in grafana or alert/monitoring systems)
I think that using template for graphite metric formatting makes changes to metrics name require more explicit intent rather then just adding/playing with tags.

**Comment by alhardy** [comment]
@Yshayy any chance you could submit a PR for this? I'm focusing the new features in App.Metrics core at the moment.

**Comment by alhardy** [comment]
https://github.com/alhardy/AppMetrics.Extensions.Graphite/issues/10 is a start to this, just need to make the GraphitePayloadBuilder generic so for customization and expose a property on the reporter config, see the HttpReporter for example https://github.com/alhardy/AppMetrics.Reporters/issues/19#issuecomment-304450246.

Then all that is required is to implement a custom `GraphitePayload` and `GraphitePoint`
